# This job finds secrets in a git repository using Gitleaks, generates a JSON report based on the findings from Gitleaks
# by extracting only the relevant information, finds the commit id and commit author for each finding, updates an Atlassian
# Confluence page with the secrets found based on that generated report and finally sends an alert on Slack.

on:
  workflow_call:
    inputs:
      CONFLUENCE_ENABLED:
        description: "Whether to enable reporting on Atlassian Confluence or not"
        required: true
        type: string
      CONFLUENCE_PAGE_TITLE:
        description: "Atlassian Confluence page title (e.g., 'Secrets Detected in the Git Repositories')"
        required: true
        type: string
      CONFLUENCE_PAGE_SPACE:
        description: "Atlassian Confluence page space (e.g., docs)"
        required: true
        type: string
      SLACK_ENABLED:
        description: "Whether to enable notifications on Slack or not"
        required: true
        type: string
    secrets:
      CONFLUENCE_SITE:
        description: "Atlassian Confluence host link (e.g., https://mydomain.atlassian.net)"
        required: true
      CONFLUENCE_USER_EMAIL_ID:
        description: "Atlassian Confluence user email ID (e.g., myname@mydomain.com)"
        required: true
      CONFLUENCE_USER_TOKEN:
        description: "Atlassian Confluence user token"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Slack Webhook URL (e.g., https://hooks.slack.com/services/__REDACTED__/__REDACTED__/__REDACTED__)"
        required: true
      SLACK_API_TOKEN:
        description: "Slack API Token (e.g., xoxb-__REDACTED__-__REDACTED__-__REDACTED__)"
        required: true

jobs:
  find-and-report-secrets-in-code:
    runs-on: ubuntu-latest
    container:
      image: abdullahkhawer/find-and-report-secrets-in-code:1.3.0
      env:
        CONFLUENCE_ENABLED: ${{ inputs.CONFLUENCE_ENABLED }}
        CONFLUENCE_SITE: ${{ secrets.CONFLUENCE_SITE }}
        CONFLUENCE_USER_EMAIL_ID: ${{ secrets.CONFLUENCE_USER_EMAIL_ID }}
        CONFLUENCE_USER_TOKEN: ${{ secrets.CONFLUENCE_USER_TOKEN }}
        CONFLUENCE_PAGE_TITLE: ${{ inputs.CONFLUENCE_PAGE_TITLE }}
        CONFLUENCE_PAGE_SPACE: ${{ inputs.CONFLUENCE_PAGE_SPACE }}
        SLACK_ENABLED: ${{ inputs.SLACK_ENABLED }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        REMOTE_PATH_TO_GIT_REPO: ${{ github.server_url }}/${{ github.repository }}
        BRANCH_NAME: ${{ github.ref_name }}
        REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
      - name: Find secrets and generate custom report
        run: |
          export LOCAL_PATH_TO_GIT_REPO=$(pwd)
          export PATH=$PATH:/usr/local/gitleaks
          cd /find-and-report-secrets-in-code/
          bash ./gitleaks.sh
          cp ./gitleaks-report.json $LOCAL_PATH_TO_GIT_REPO/gitleaks-report.json
      - name: Upload generated custom report as artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report.json
          path: gitleaks-report.json
      - name: Update Confluence page and/or send alert on Slack
        if: ${{ inputs.SLACK_ENABLED == '1' || inputs.CONFLUENCE_ENABLED == '1' }}
        run: |
          cd /find-and-report-secrets-in-code/
          python3 main.py "Europe/Amsterdam" $REPO_NAME $BRANCH_NAME ${{ steps.artifact-upload-step.outputs.artifact-url }}
